---
title: "Research Data Management @ FGB"
date: "`r Sys.Date()`; version 1.5"
output: 
  html_document:
    theme: cerulean
    includes: 
      after_body: footer.html
---


<style type="text/css">

/* need to ensure all text is in Roboto so as to be in-line with VU house style*/

body {
  font-family: 'Roboto', sans-serif;
}

.main-container {
  max-width: 80%;
  margin-left: auto;
  margin-right: auto;
  padding-top: 5%;
  padding-bottom: 30%;
  padding-right: 10%;
  padding-left: 10%;
}

h1.title {
  font-size: 28px;
  text-align: center;
}

h4.date { /* this is to affect the size of the date text in the YAML when it prints in html  */
  font-size: 20px;
  text-align: center;
}

p, summary {
  font-size: 18px;
}

li {
  font-size: 18px;
  margin: 5px;
}




</style>

\
\
\

# Blog: Announcements and Updates

* [Blog](blog/){target="_blank"}

# Frequently asked questions on RDM, Privacy & Security

* [FGB FAQ](FAQ/){target="_blank"}


# Policies

* [FGB RDM policy](Policies/FGB_RDM_Policy.html){target="_blank"}
* [FGB policy positions on the GDPR](Policies/FGB_Policy_Positions_GDPR.html){target="_blank"}


# Research Data Management Guidance

* [FGB RDM pages on VUweb](https://vu.nl/en/employee/research-data-management-fbms){target="_blank"}
* Archiving guidance
  + [Full FGB archiving guidelines](rdm/archiving/ArchivingGuidelinesFull.html){target="_blank"}
  + [Summary of FGB archiving guidelines](rdm/archiving/ArchivingGuidelinesSummary.html){target="_blank"}
  + [Guidance Policy - Digitizing Paper Informed Consent Forms](rdm/archiving/DigitizingICFs.html){target="_blank"}
* [RDM Definitions](rdm/definitions/Definitions.html){target="_blank"}
* RDM documentation guidance
  + [Codebooks](rdm/documentation/Codebooks.html){target="_blank"}
* RDM tools
  + [Castor instructions](rdm/tools/Castor_spelregels.html){target="_blank"}
  + [YODA instructions](rdm/tools/YODAInstructionsFGB.html){target="_blank"}
  + [Qualtrics & Survalyzer instructions](rdm/tools/SecureUseOfQuestionnaireTools.html){target="_blank"}
  

# Security Guidance

* [Security basics](Security/SecurityBasics.html){target="_blank"}
* Privacy risk guidance
    + [Privacy risks guidance app](https://risk_levels_app.rshiny.labs.vu.nl/){target="_blank"}
    + [Privacy risks explained](Security/PrivacyRisks.html){target="_blank"}
* [De-identification of data](Security/Deidentification.html){target="_blank"}
* [Encryption](Security/Encryption.html){target="_blank"}
* [Secure storage guide](Security/Storage.html){target="_blank"}
* [Secure digital data transfer guide](Security/DigitalTransfer.html){target="_blank"}
* [Secure physical data transport guide](Security/PhysicalTransport.html){target="_blank"}
* [Security for students](Security/SecurityForStudents.html){target="_blank"}

# Legal Guidance

* [GDPR take-home points](legal/GDPRBasics.html){target="_blank"}
* Informed consent guidance
    + [Informed Consent Form and Information Letter Checklist](legal/ICFChecklist.html){target="_blank"}
    + [Informed consent generator](https://icf.rshiny.labs.vu.nl/){target="_blank"}
* [How to use ZIVVER to obtain digital consent](legal/ZIVVERdigitalConsent.html){target="_blank"}
* [Workflow for processing standard privacy agreements](Images/privacy_agreement_flow_fgb_2025.pdf){target="_blank"}



# Financial Concerns

* [Bulk participant declarations form](finance/participant_declarations_instructions_EN.html){target="_blank"}
* [Registration form for WMO research requiring participants' insurance](https://fgbto3-web.labs.vu.nl/rdm/wmo-insurance/){target="_blank"}
