---
title: "Ethics @ FGB: Ethical Review Processes"
date: "`r Sys.Date()`; version 1.0"
output: 
  html_document:
    theme: cerulean
    includes: 
      after_body: 
        - ../footer.html
        - wmoJavaScript.html
---


<style type="text/css">

/* need to ensure all text is in Roboto so as to be in-line with VU house style*/

body {
  font-family: 'Roboto', sans-serif;

}

.main-container {
  max-width: 80%;
  margin-left: auto;
  margin-right: auto;
  padding-top: 5%;
  padding-bottom: 30%;
  padding-right: 10%;
  padding-left: 10%;

}

h1.title {
  font-size: 28px;
  text-align: center;
}

h4.date { /* this is to affect the size of the date text in the YAML when it prints in html  */
  font-size: 20px;
  text-align: center;
}

p, summary {
  font-size: 18px;
}

li {
  font-size: 18px;
  margin: 5px;
}

#guidance-wrapper {
    position: relative;

}


/* This ensures the wrapper grows to the height of the visible content */
#guidance-wrapper::after {
    content: "";
    display: block;
    height: var(--wrapper-height, 0px);
}

  .guidance, .quiz {
    opacity: 0;
    transform: translateX(100%); /* Start off to the right */
    transition: opacity 0.6s ease, transform 0.6s ease;
    position: absolute;
    left: 0;
    right: 0;
    pointer-events: none;
}

 .guidance.show, .quiz.show {
      position: relative;
      opacity: 1;
      transform: translateX(0); /* Slide into place */
      pointer-events: auto;
     /* z-index: 2;  while there is overlap this determines which message is on top */
    }
    
  .guidance.hide-left, .quiz.hide-left {
      opacity: 0;
      transform: translateX(-100%); /* Slide out to the left */
     /*  z-index: 1; while there is overlap this determines which message is on top */
  }


    

.btn {
  width: 50%;
}

#footer {
  position: relative;
  bottom: 0;
}

</style>





### Which ethical review process do you need information on? {#intro}

<form id="whichRoute">
<label><input type="radio" name="routePicker" id="displayWMO" value="wmo">WMO research review process </label><br>
<label><input type="radio" name="routePicker" id="displayNonWMO" value="nwmo">Non-WMO declaration process </label><br>
<label><input type="radio" name="routePicker" id="displayVCWE" value="vcwe"> Standard FGB ethical review for non-clinical research </label><br>
<label><input type="radio" name="routePicker" id="displayQuiz" value="quiz"> I need help to figure out what process(es) apply to me </label><br>
</form>

<div id = "guidance-wrapper">
<div  class = "guidance">

## Please contact help!!! {#helpGuidance}

</div>

<div class = "guidance">

## This is guidance on the WMO review process {#wmoGuidance}

</div>


<div class = "guidance">

## This is guidance on the process of obtaining a non-WMO declaration {#nwmoGuidance}

</div>


<div  class = "guidance">

## This is guidance on the standard FGB VCWE ethical review process {#vcweGuidance}

</div>

<div  class = "guidance">

## Here come a bunch of questions!!! {#quizGuidance}

<div class = "quiz"> 

### Are your participants subjected to an experimental intervention? {#quest1}

<form id="answersQ1" class = "answers" data-answered = "false"> <!-- the data-* attribute is a way to add some extra attributes to an element where * is my choice of name -->
<label><input type="radio" name="expCond" id="answer1Yes" value="yes">Yes</label><br>
<label><input type="radio" name="expCond" id="answer1No" value="no">No</label><br>
<label><input type="radio" name="expCond" id="answer1Unsure" value="unsure"> I'm not sure</label><br>
</form>

<!-- create button that will only show if answers already filled in -->
<button class="manual-next btn btn-primary btn-sm" id="btn1_2" style="display:none;">Next</button>

</div>

<div class = "quiz"> 

### Will your research involve semi-invasive procedures, namely drawing blood and/or using rectal thermometers? {#quest2}

<form id="answersQ2" class = "answers" data-answered = "false">
<label><input type="radio" name="invProc" id="answer1Yes" value="yes">Yes</label><br>
<label><input type="radio" name="invProc" id="answer1No" value="no">No</label><br>
<label><input type="radio" name="invProc" id="answer1Unsure" value="unsure"> I'm not sure</label><br>
</form>

<div class="d-grid gap-2">
<button id="btn2_1" class="btn btn-primary btn-sm">Back</button> 
<!-- create button that will only show if answers already filled in -->
<button class="manual-next btn btn-primary btn-sm" id="btn2_3" style="display:none;">Next</button>
</div>

</div>

<div class = "quiz"> 

### Is the focus of your research clinical in nature, even though participants are not subject to clinical interventions? {#quest3}

<form id="answersQ3" class = "answers" data-answered = "false">
<label><input type="radio" name="clinNat" id="answer1Yes" value="yes">Yes</label><br>
<label><input type="radio" name="clinNat" id="answer1No" value="no">No</label><br>
<label><input type="radio" name="clinNat" id="answer1Unsure" value="unsure"> I'm not sure</label><br>
</form>

<button id="btn3_2" class="btn btn-primary btn-sm">Back</button> 

</div>

</div>

</div>







