---
title: "FGB Security Tips: Assessing Privacy Risks"
date: "`r Sys.Date()`; Version 2.2"
output: 
  html_document:
    theme: cerulean
    anchor_sections: TRUE
    includes: 
      after_body: ../footer.html
---


<style type="text/css">

/* change font for whole text so that it's in line with house style. For webpages that is Roboto  */

body {
  font-family: 'Roboto', sans-serif;
}

/* the follow CSS code allows me to take the automatically included anchor sections (that I made active in the YAML with anchor_sections: TRUE) and change the icon that is shown from a hash to a link symbol from the bootstrap icon library */

a.anchor-section::before {
    content: "&#xe144";
    font-family: 'Glyphicons Halflings';
}

.main-container {
  max-width: 100%;
  margin-left: auto;
  margin-right: auto;
  padding-top: 5%;
  padding-bottom: 15%;
  padding-right: 10%;
  padding-left: 10%;
}

h1.title {
  font-size: 28px;
  text-align: center;
}

h4.date { /* this is to affect the size of the date text in the YAML when it prints in html  */
  font-size: 20px;
  text-align: center;
}

p {
  font-size: 18px;
}

li {
  font-size: 18px;
  margin: 5px;
}

/* improve contrast for all a-tags and headers for accessibility */

a {
  color: #157bb7;
}

h1, h2, h3, h4 {
  color: #105d89;
}

table {
  width: 100%;
}

table, td { 
  padding: 10px;
  vertical-align: top;
  border-bottom: 1px solid #ddd;
  font-size: 16px;
}

#red {
  border-top-style: solid;
  border-bottom-style: solid;
  border-width: 3px;
  border-color: #ed0000;
}

#orange {
  border-top-style: solid;
  border-bottom-style: solid;
  border-width: 3px;
  border-color: #ff9000;
}

#yellow {
  border-top-style: solid;
  border-bottom-style: solid;
  border-width: 3px;
  border-color: #ffDf00;
}

#green {
  border-top-style: solid;
  border-bottom-style: solid;
  border-width: 3px;
  border-color: #379e00;
}

#blue {
  border-top-style: solid;
  border-bottom-style: solid;
  border-width: 3px;
  border-color: #6e99c4;
}

/* changed color of footnotes per 2022-11-02 from #989898 to #737373 to improve accesibility (contrast of color) */

.footnotes {
  color: #737373;
}

#confidtable {
  width: 80%;
  margin-left: 5%;
}

#confidtable th {
  text-align: left;
}



#confidtable th  {
  border-width: 3px;
}

/* to change the color from the second column onwards select th + th. This will change everything from the second column onwards. So then for the third column do th + th + th which will start the selection from the third column and to select the last column just select th:last-child */

#confidtable th + th {
  border-color: #ed0000;
}

#confidtable th + th + th {
  border-color: #ff9000;
}

#confidtable th + th + th + th {
  border-color: #ffDf00;
}


#confidtable th:last-child {
  border-color: #6e99c4;
}


#indent {
  padding-left: 3.5em;
}

</style>


\ <!--this adds a space  -->

Data about human beings are very rarely [anonymous](../Images/Anonymization-reference-card-for-researchers.pdf){target="_blank"}. Even if the data do not contain information such as name or address, the data may still pose privacy risks to the people they are about, especially if it is possible to re-identify individuals within the data you are using for your research. To manage these risks, it is important to understand how severe the risks are in your situation. The table below can be used to determine privacy risk categories for different types of data, however, it's recommended to now use the [privacy risk app](https://risk_levels_app.rshiny.labs.vu.nl/){target="_blank"} (which is based on the table below) because the app offers advice that is specific to your needs. 

Privacy risks are based on three pillars: the [vulnerability](#vulnerability) of the research subjects, the [re-identifiability of the data](#reID) and the [risk of harm](#harm) to the research subjects that is posed by the information in the data. The guidance on this page, nor on the [privacy risk app](https://risk_levels_app.rshiny.labs.vu.nl/){target="_blank"}, cannot capture every possible situation, so think of this advice as a spectrum. If in doubt, opt for a higher risk category. Also, not all of the data in your research will have the same level of privacy risk and the privacy risks for each type of data may change as you clean, recode and modify the data from a [raw](../rdm/definitions/Definitions.html#rawdata){target="_blank"} to [processed](.., /rdm/definitions/Definitions.html#processeddata){target="_blank"} form. You should assess the risks for each separate [data asset](../rdm/definitions/Definitions.html#dataasset){target="_blank"} and also consider how each data asset's risk will change over the course of the research life cycle. If some data are higher risk than others, you can store these data separately in a more secure storage option.

Once you've determined the privacy risk category for each data asset, you can use these categories to inform your choices about how your data can be [de-identified](Deidentification.html){target="_blank"}, [safely used by students/interns](SecurityForStudents.html){target="_blank"}, [safely transported physically](PhysicalTransport.html){target="_blank"}, [securely transferred digitally](DigitalTransfer.html){target="_blank"}, and [securely stored](Storage.html){target="_blank"}.

--------------------

\

### Privacy Risk Categorization {#privRskCat}
  
## {.tabset .tabset-fade}


### Red Data {#red}

  
<!-- &nbsp; can be used to make the columns wider. it's a blank space  &bull; is the html code for a bullet point-->

| | |
| --- | --------------- |
| _Privacy Risk_ | Very high-risk |
| _Description_ | &bull; [Directly identifying](#reID) data from [vulnerable people](#vulnerability) containing information that [elevate the risks of harm](#harm) |
| _Impact of a Breach_ | &bull; Severity of harm to research subjects and/or damage to the reputation of VU Amsterdam would be very high <br>&bull;	The likelihood of harm or damages after a breach is very high |
| _Examples_ | &bull; Video interviews with children talking about abuse <br>&bull; Raw transcripts of interviews with refugees talking about their home country <br>&bull;	Diaries from vulnerable patients with mental or physical conditions/disabilities <br>&bull;	Raw transcripts of interviews with non-white employees describing their satisfaction with their employer <br>&bull;	Raw neuroimages (not de-faced) of vulnerable subjects with serious medical or mental health conditions <br>&bull;	Non-pseudonymous genetic data from vulnerable subjects that indicates a risk for disease or disorders  |
  
### Orange Data {#orange}
  
| | |
| --- | --------------- |
| _Privacy Risk_ | High-risk |
| _Description_ | &bull; [Directly identifying](#reID) data from [non-vulnerable people](#vulnerability) containing information that does [NOT elevate the risks of harm](#harm) <br> **OR**<br>&bull; [Directly identifying](#reID) data from [vulnerable people](#vulnerability) containing information that does [NOT elevate the risks of harm](#harm)  <br>**OR**<br>&bull; [Directly identifying](#reID) data from [**non-vulnerable** people](#vulnerability) containing information that [elevate the risks of harm](#harm)  <br>**OR**<br>&bull; Data from [vulnerable people](#vulnerability) containing information that [elevate the risks of harm](#harm) that has been made slightly [less identifiable](#reID) by removing easily identifying information (e.g. name, contact information) |
| _Impact of a Breach_ | &bull;	Severity of harm to research subjects and/or damage to the reputation of VU Amsterdam would be high <br>&bull;	The likelihood of harm or damages after a breach is moderate to high |
| _Examples_ | &bull;	Key files containing names and contact information of research subjects<br>&bull; Data containing date of birth and 6-digit postal code of research subjects <br>&bull; Video observations of children playing<br>&bull;	Video observations of team-building activities<br>&bull;	Raw neuroimages (not de-faced) of non-vulnerable subjects <br>&bull;	Raw questionnaire data about sensitive or stigmatized topics<br>&bull;	Raw questionnaire data from vulnerable subjects containing detailed demographic information<br>&bull;	Genetic data from non-vulnerable subjects |



### Yellow Data {#yellow}
  
| | |
| --- | --------------- |
| _Privacy Risk_ | Medium to high risk |
| _Description_ | &bull;	Data from [non-vulnerable people](#vulnerability) containing information that does [NOT elevate the risks of harm](#harm) that been made slightly [less identifiable](#reID) by removing easily identifying information (e.g. name, contact information) <br> **OR**<br>&bull; Data from [vulnerable people](#vulnerability) and/or containing information that does [NOT elevate the risks of harm](#harm) that has undergone additional [de-identification steps](Deidentification.html){target="_blank"} beyond the removal of easily identifying information (e.g. name, contact information) |
| _Impact of a Breach_ | &bull;	Severity of harm to research subjects and/or damage to the reputation of VU Amsterdam would be moderate to high <br>&bull; The likelihood of harms or damages after a breach is moderate to low |
| _Examples_ | &bull;	IP- and MAC-addresses of research subjects <br>&bull; Raw questionnaire data from non-vulnerable subjects containing demographic information<br>&bull;	Questionnaire data about sensitive/stigmatized topics and/or vulnerable people that has been processed to make re-identification more difficult<br>&bull;	Video recordings with faces blurred and voices modified<br>&bull;	Transcripts of interviews in which the identifying information is replaced with pseudonyms<br>&bull;	Repeated physical measurements on vulnerable subjects that include the dates and times the measurements occurred<br>&bull;	De-faced neuroimages of vulnerable people<br>&bull;	Extensive kinematic measurements that are used to identify sensitive information such as movement disorders |

### Green Data {#green}
  
| | |
| --- | --------------- |
| _Privacy Risk_ | Medium to low risk |
| _Description_ | &bull;	Data from [non-vulnerable people](#vulnerability) containing information that does [NOT elevate the risks of harm](#harm) that has undergone additional [de-identification steps](Deidentification.html){target="_blank"} beyond the removal of easily identifying information (e.g. name, contact information) |
| _Impact of a Breach_ | &bull;	Severity and likelihood of harm to research subjects after a breach are low<br>&bull;	Damage to the reputation of VU Amsterdam is still possible, but likelihood is lower and the impact would be less severe |
| _Examples_ | &bull;	Data that contain a unique record for at least one research subject, e.g.:<br>&nbsp;&nbsp;-	De-faced neuroimages of non-vulnerable people<br>&nbsp;&nbsp;-	Extensive kinematic measurements from non-vulnerable subjects<br>&nbsp;&nbsp;-	Highly variable physical measurements, e.g. blood pressure, heart rate, blood glucose, body temperature<br>&nbsp;&nbsp;-	Any other datasets that contain sufficient information to create a unique record for one or more research subjects |

### Blue Data {#blue}
  
| | |
| --- | --------------- |
| _Privacy Risk_ | Little to no risk |
| _Description_ | &bull;	Data that cannot be [re-identified](#reID) whatsoever, regardless of the [vulnerability](#vulnerability) of the research subjects or the [risks of harm](#harm) posed by the information |
| _Impact of a Breach_ | &bull;	Research subjects will suffer no direct[**](#NB) harm and VU Amsterdam will suffer no damages to its reputation |
| _Examples_ | &bull;	Likert scale responses in a questionnaire<br>&bull;	Coded qualitative data<br>&bull;	Summary statistics <br><br>**NB**: If your data can still be linked to identifying information (e.g. through participant identifiers that link to a separate [key file](../rdm/definitions/Definitions.html#keyfile){target="_blank"}), the data are not anonymous and therefore not "blue". Such data would be "green" or "yellow" depending on the sensitivity of the information and vulnerability of the research subjects. If it is possible _and_ appropriate to delete this last link to the identifying information, then the data can be considered anonymous. |

##### {#NB}
###### **NB: Although research subjects will not be directly harmed, the conclusions drawn from research results or the misuse of published research software can impact the wider population to which the research subjects belong. Such ethical considerations should be discussed with the [FGB Scientific and Ethical Review Board](https://vu.nl/en/about-vu/faculties/faculty-of-behavioural-and-movement-sciences/more-about/faculty-committees){target="_blank"}.


##

\



### Confidentiality Risk versus Privacy Risk {#confidentiality}

Confidentiality and privacy overlap, however, confidentiality is about how a data breach would impact our institution while privacy considers how a data breach would impact our research subjects. Confidentiality concerns have been taken into consideration in the guidance above so that the privacy risks you determine can also be viewed as confidentiality risks.

If your data are not about human subjects, they may still need to be kept [confidential](../rdm/definitions/Definitions.html#confidentialdata){target="_blank"}, for example, when working with business secrets or intellectual property. If you are working with a third party, especially a business, they may require you to keep their data confidential. Below are some examples of different confidentiality risks for non-human data:

  

<div id="confidtable">

| | Red Data | Orange Data | Yellow Data | Blue Data* |
| -------- | ----------- | ----------- | ----------- | ----------- | 
| _Confidentiality Risk_ | Very high-risk | High-risk | Medium-risk | Low-risk | 
| _Examples_ |&bull; Data that are classified as "secret" | &bull; Commercially sensitive data <br/>&bull; Politically sensitive data <br/>&bull; Data subject to non-disclosure agreements | &bull; Patents & other intellectual property <br/> &bull; AI algorithms that could benefit other countries <br/> &bull; Unpublished research output with novel results <br/> &bull; Internal procedures and policies | &bull; Data that can be publicly disclosed |
  
</div>

* Green data aren't listed here because the primary distinction between Green and Blue _privacy_ risks is that Green data are still technically personal data while Blue data are anonymous or anonymized data. There isn't a comparable category to Green data when assessing the confidentiality risks of non-personal data, therefore low confidentiality risk data should be handled as Blue data. Be aware that although Blue data can be publicly disclosed, you should assess, when publishing these data, whether there should be any limitations on how these data are reused. Even publicly available data can have limits placed on how they are reused by applying [restrictive licenses](https://creativecommons.org/about/cclicenses/){target="_blank"}, such as those that don't allow reuse for commercial purposes. More information on data licensing is found [here](https://dmeg.cessda.eu/Data-Management-Expert-Guide/6.-Archive-Publish/Publishing-with-CESSDA-archives/Licensing-your-data){target="_blank"}.

--------------------

\

### Important Factors in Privacy Risk {#privacyRiskFactors}

\

#### The ease with which research subjects can be re-identified in the data: {#reID}

* Data are [personal data](../rdm/definitions/Definitions.html#personaldata){target="_blank"} if they are [directly identifying](../rdm/definitions/Definitions.html#directID){target="_blank"} or [indirectly identifiable](../rdm/definitions/Definitions.html#indirectID){target="_blank"}: 
  + Directly identifying data are what most people think of as personal data: name, contact information, facial images etc. This information isn't _always_ directly identifying (e.g. a name like Jan Smit is very common in The Netherlands, so that name alone might not be enough to identify someone). Regardless, it's generally agreed that these types of data should be handled with extra care and that these types of data should be ideally stored separately from other research data. 
  + Indirectly identifiable data can also be referred to as pseudonymous data (although there are some caveats[^1] to this). The ease with which a research subject could be *re-identified* from indirectly identifiable data depends on several factors such as: 
    + How much information has been collected about each research subject? 
    + How specific is the information about each research subject?
    + How unique is the information about each research subject?
      + _Unique information may be a result of one variable with extreme values or a combination of several variables that create a record that is distinct from all others in the dataset_
    + Could the data be linked to publicly available information, such as social media profiles?
  + It is *very* important to consider how easily indirectly identifiable data can be re-identified. If only the most cursory of efforts has been made to de-identify the data (most commonly, only removing names and contact information from the dataset), then the research subjects usually remain at risk of re-identification due to the wealth of other information present in the dataset. If someone tells you a dataset is "pseudonymous", it is also a good idea to assess how easily these data could be re-identified, since not everyone has the same idea about what pseudonymous means^[1](#fn1)^. 


* As long as data are identifiable, they cannot be referred to as [anonymous data](https://www.lcrdm.nl/files/lcrdm/2020-01/Anonymization%20-%20reference%20card%20for%20researchers.pdf){target="_blank"} and the legal rules of the [GDPR](https://assets.vu.nl/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/57e5d5e6-54dc-4904-be0d-0baaa6cc8b73/AVG%20Take-home%20points%20voor%20FGB%20onderzoekers%3F.pdf){target="_blank"} must be followed. This means the GDPR applies to pseudonymous data.

* Not all identifiable data pose the same level of privacy risk: oftentimes, raw data often pose higher privacy risks because of greater re-identifiability (e.g. video recordings), and therefore require additional data protection measures (such as [high security storage](Storage.html){target="_blank"}); as the data are cleaned, recoded and analysed they become less identifiable (e.g. coded interactions) and require fewer data protection measures. [De-identification](Deidentification.html){target="_blank"} is therefore an important part of data processing that can be used to protect the privacy of your research participants; the identifiability of the data is the only factor you can change since it's not possible to reduce the vulnerability of your research subjects or the sensitivity of your research topic.

\

#### The vulnerability of the research subjects: {#vulnerability}

* Vulnerable research subjects have an additional risk of harm (socially, physically, emotionally, financially) if their personal information is made public. The greater the vulnerability of the research subjects, the greater the potential for serious harm.

* Vulnerable research subjects include, but are not limited to: 
  * children
  * people who identify as LGBTQ+
  * refugees
  * ethnic or religious minorities

* When assessing the vulnerability of the research subjects, bear in mind that we are looking at what vulnerability characteristics are known or disclosed within the data. If you are not actively studying a specific vulnerable population and you do not need to collect data that could identify someone as vulnerable, then that information should not be collected in order to minimize the risks to the research subjects. For example, if you do not need to know the ethnicity or sexuality of your research subjects, you should not collect that information within your research data. That way you can minimize the overall privacy risks by minimizing the vulnerabilities of the research subjects studied. However, there may be situations where collection of this information is unavoidable, e.g. video recordings of research subjects will also collect skin colour and any religious clothing. Keep such cases in the back of your mind when assessing the overall privacy risks; even if you are not actively studying a vulnerable population, consider whether you will collect data that could identify someone as part of a vulnerable population when you are assessing the [risks of harm](#harm) to the research subject.

\

<div id="sensitivity"></div> <!---- put an extra div ID here to allow the tag using sensitivity to continue to work while updating all hyperlinks -->

#### The risk of harm posed by the information being used: {#harm}

* The risk of harm posed by the information in the data is the most complex and subjective consideration in assessing the privacy risks. Your goal is to consider what information your research data contain and whether that information, either in combination with or in addition to the vulnerability of your research subjects, poses elevated risks of harm to the research subjects. Information that could increase the risks of harm to your research subjects include subject matter that is sensitive, taboo or stigmatized in nature. The risk of harm is elevated if the research subjects would experience further risks to their well-being if the information is made public beyond the disclosure of their vulnerability characteristics. For example, a dataset containing the names of LGBTQ research subjects is only high-risk (orange data) as long as the only information leaked is the research subjects' names. Such a situation is not ideal, but no further information beyond names has been disclosed. However, if the leaked information included information about the research subjects' sexuality and their sexual experiences, that would constitute an elevated risk of harm due to the information contained in the data (i.e. very high-risk or red data). If the leaked data included just names, but it was known that the research population being studied was entirely LGBTQ, this may or may not constitute an elevated risk of harm, i.e. the data may be orange or red. The data would be more likely orange if your population consists of openly queer research subjects, whereas it would be better to consider the data red if your subjects are still in the closet. Because of these complex nuances, it is imperative that you thoroughly contemplate how much damage the public disclosure of your research data would pose to your research subjects.
  + If in doubt, contact the [FGB Privacy Officer](mailto:research.data.fgb@vu.nl) for support.

* Some other topics that *may potentially* increase the risk of harm to your subjects, include:
  * employment status 
  * income and other financial data
  * student grades and performance
  * location data

<div id="indent">  
The risk of harm in these cases will often depend on the vulnerability characteristics of the research subjects, for example, employment status of the average Dutch person is someone sensitive, but does not pose an elevated risk, while employment status of an asylum seeker could have political ramifications for the research subject in question and may risk their safety and well-being.
</div>

* If the data are ["special" under the GDPR](https://fgb-rdm.nl/legal/GDPRBasics.html#special){target="_blank"} the risk of harm *may* be elevated but this is not always the case; if your research data fall into the "special" category it is a warning sign to thoroughly assess for elevated risks of harm posed by the data.
  + "Special" data are subject to additional legal requirements under the GDPR regardless of the risks of harm posed by these data. More information is found on the [GDPR Take-Home Points page](https://fgb-rdm.nl/legal/GDPRBasics.html#special){target="_blank"}
  + If your data pose additional risks to the research subjects, but are not "special" data types under the GDPR, they do not need to meet the additional legal requirements for "special" data. However, these data should of course be treated with extra care because of the risk to the research subjects' privacy and well-being.

* Elevated risks of harm can also apply to non-personal data, such as a company’s financial records. If the disclosure of this information could negatively impact an individual or organisation, this suggests a potentially elevated [confidentiality risk](#confidentiality).


\





<!-- Footnotes -->

# {#pseudonymization}

[^1]: The legal definition of pseudonymization according to the [GDPR](https://gdpr-info.eu/art-4-gdpr/){target="_blank"} is quite strict. Essentially, according to the GDPR, pseudonymous data requires additional information for the data to be re-identified and if that additional information is deleted, the data become anonymous. In real life, the situation is more complicated. A dataset with no directly identifying data may still contain indirectly identifiable data (often demographic information) that can be used to single out unique records, which could then be used to re-identify people using publicly available information or based on context clues. You could [de-identify](Deidentification.html){target="_blank"} this dataset further and, if done correctly, you would ensure that the only way to re-identify the research subjects would be with an identification code and a key file. Both the former and latter versions of this dataset would be called "pseudonymized" by a layperson, but under the GDPR only the latter version is legally considered to be pseudonymized. The main takeaway from this is that even if someone says their data are pseudonymous, you should investigate to what extent the data have been pseudonymized: do they mean the GDPR's strict definition of pseudonymized or do they simply mean that the directly identifying data have been removed from the dataset?

