---
title: "Blog: Announcements and Updates"
date: "`r Sys.Date()`; version 1.0"
output: 
  html_document:
    theme: cerulean
    includes: 
      after_body: ../footer.html
---

<style type="text/css">

/* need to ensure all text is in Roboto so as to be in-line with VU house style*/

body {
  font-family: 'Roboto', sans-serif;
}

.main-container {
  max-width: 80%;
  margin-left: auto;
  margin-right: auto;
  padding-top: 5%;
  padding-bottom: 30%;
  padding-right: 10%;
  padding-left: 10%;
}

h1.title {
  font-size: 28px;
  text-align: center;
}

h4.date { /* this is to affect the size of the date text in the YAML when it prints in html  */
  font-size: 20px;
  text-align: center;
}

p, summary {
  font-size: 18px;
}

li {
  font-size: 18px;
  margin: 5px;
}

table {
  width: 80%;
}

table, td { 
  vertical-align: top;
  text-align: left;
  border-bottom: 1px solid #ddd;
  font-size: 18px;
}


table tr td:first-of-type {
    width: 20%;
    padding-bottom: 20px;
}
table tr td:nth-of-type(2) {
    width: 80%;
    padding-bottom: 20px;
}

</style>

\
\
\


*Ok, so technically this isn't really a proper blog right now (i.e. you can't subscribe via RSS), but this is the place you can go to see the latest major changes/updates/announcements related to data support in FGB. I also only implemented this "blog" as of 30 April 2025 and I'm not going to retroactively post previous updates, so apologies if you want to know the history of the changes to these support pages. You'll just have to use your imagination!*

\
\

| | |
| -- | ----------------------- |
| 2025/08/27; Jessica Hrudey | Added extra header for privacy risks table to [privacy risks page](../Security/PrivacyRisks.html){target="_blank"} and added extra definitions for types of data publishing to [Definitions page](../rdm/definitions/Definitions.html){target="_blank" |}
| 2025/08/14; Jessica Hrudey | Redefined sensitivity of data to risk of harm on the [privacy risks page](../Security/PrivacyRisks.html){target="_blank"} and on the [GDPR Take-home points page](../legal/GDPRBasics.html){target="_blank"} to more clearly define what is represented by that concept |
| 2025/08/11; Jessica Hrudey | Updated [archiving guidelines summary](../rdm/archiving/ArchivingGuidelinesSummary.html){target="_blank"} to include DataverseNL as an archiving location for Green data |
| 2025/07/22; Jessica Hrudey | Put content from [Qualtrics](https://fgbto3-web.labs.vu.nl/rdm/Images/SendingSurveysinQualtricsWithoutUploadingEmails.pdf){target="_blank"}/[Survalyzer](https://fgbto3-web.labs.vu.nl/rdm/Images/SendingSurveysinSurvalyzerWithoutUploadingEmails.pdf){target="_blank"} PDF manuals on how to work around e-mail distribution systems into text of [html page on use of Qualtrics and Survalyzer](../rdm/tools/SecureUseOfQuestionnaireTools.html){target="_blank"} |
| 2025/05/19; Jessica Hrudey | Added fifth policy principle to [FGB RDM Policy](../Policies/FGB_RDM_Policy.html){target="_blank"} requiring pre-registration of all research projects that require a data management plan |
| 2025/05/15; Jessica Hrudey | Updated and converted PDF on secure use of qualtrics and survalyzer to [new html page on use of Qualtrics and Survalyzer](../rdm/tools/SecureUseOfQuestionnaireTools.html){target="_blank"}.
| 2025/04/30; Jessica Hrudey | Updates to [FGB RDM Policy](../Policies/FGB_RDM_Policy.html){target="_blank"} and [FGB Policy Positions on the GDPR](../Policies/FGB_Policy_Positions_GDPR.html){target="_blank"}: <br>&bull; Minor text adjustments to bring in-line with [VU RDSM Policy v3](https://rdm.vu.nl/public/policies-regulations/RDSM-policy-VU-EN-v3.0.pdf){target="_blank"} - primarily, addition of "software management" changing RDM to RDSM (*yes, we know what it sounds like*) <br>&bull; Streamlining info on researcher responsibilities re: privacy agreements workflows <br>&bull; Update to information on contract signing mandates/responsibilities by faculty director vs dept managers <br> Updates to [Archiving Guidelines](../rdm/archiving/ArchivingGuidelinesFull.html){target="_blank"} & [Summary](../rdm/archiving/ArchivingGuidelinesSummary.html){target="_blank"}: <br>&bull; Creation of [Digitization of ICFs guidelines](../rdm/archiving/DigitizingICFs.html){target="_blank"} <br>&bull; Update to text of archiving guidelines regarding paper archiving and destruction after digitization, with crossrefs to new digitilization guide |
| 2025/04/30; Jessica Hrudey | First post (hello world, yadayada) <br> Created this "not-a-blog" |
