---
title: "RDM Tools @ FGB: Castor 'Spelregels'"
date: "`r Sys.Date()`; Version 1.1"
output: 
  html_document:
    theme: cerulean
    anchor_sections: TRUE
    includes: 
      after_body: ../../footer.html
---

## {#CSS}

<style type="text/css">

/* need to ensure all text is in Roboto so as to be in-line with VU house style*/

body {
  font-family: 'Roboto', sans-serif;
}

/* 2022-10-11: I made the max-width on this particular document 2000px when all the others were at 1600px; this is because I noticed an issue with the positioning of the tabsets (they aren't right next to each other as desired) when in full screen mode on the wide screen monitor. Will check if this is an issue on other pages and adjust max-width as necessary */

.main-container {
  max-width: 80%;
  margin-left: auto;
  margin-right: auto;
  padding-top: 5%;
  padding-bottom: 10%;
  padding-right: 10%;
  padding-left: 10%;
}

/* the follow CSS code allows me to take the automatically included anchor sections (that I made active in the YAML with anchor_sections: TRUE) and change the icon that is shown from a hash to a link symbol from the bootstrap icon library */

a.anchor-section::before {
    content: "&#xe144";
    font-family: 'Glyphicons Halflings';
}


h1.title {
  font-size: 28px;
  text-align: center;
}

h4.date { /* this is to affect the size of the date text in the YAML when it prints in html  */
  font-size: 20px;
  text-align: center;
}

/* improve contrast for all a-tags and headers for accessibility */

a {
  color: #157bb7;
}

h1, h2, h3, h4 {
  color: #105d89;
}

p, summary {
  font-size: 18px;
}

li {
  font-size: 18px;
  margin: 5px;
}





</style>



Castor is a data management software that is available to FGB researchers, particularly those conducting medical research. You can find all the information you need to work with Castor in this [manual](https://helpdesk.castoredc.com/hc/en-us/sections/26269456973725-Castor-CDMS-Manual){target="_blank"}. However there are some additional rules ("spelregels") you must follow to use Castor at the Faculty.

### Step 1 {#step1}

* You _**must**_ use the Castor billing code.
    + While it's possible to create an account and run a small study for free, if you do so without the billing code, the data are not sufficiently protected and you are not following GDPR requirements
    + You can request the billing code via research.data.fgb@vu.nl

### Step 2 {#step2}

* Ensure that you are using the Netherlands server for data storage
    + The Dutch version is accessed via [https://data.castoredc.com/](https://data.castoredc.com/){target="_blank"} 

### Step 3 {#step3}

* You _**must**_ activate two-factor authentication when you create your Castor account and you must keep this active the entire time you use Castor
    + Instructions on this are found [here](https://helpdesk.castoredc.com/en_US/2-introduction-and-getting-started/two-factor-authentication){target="_blank"}

### Step 4 {#step4}

* You are strongly advised to read the Castor manual, particularly the [Castor manual](https://helpdesk.castoredc.com/hc/en-us/sections/26269456973725-Castor-CDMS-Manual){target="_blank"}
    + The following sections are particularly important:
        + [How to use Castor EDC system in a secure way - Best practices](https://helpdesk.castoredc.com/en_US/2-introduction-and-getting-started/how-to-use-castor-edc-system-in-a-secure-way-best-practices){target="_blank"}
        + [Castor EDC/CMDS Tips and tricks - Before starting](https://helpdesk.castoredc.com/hc/en-us/articles/27036238817053-Castor-CDMS-Tips-tricks-Beginners){target="_blank"}
        + [The structure of Castor EDC/CDMS](https://helpdesk.castoredc.com/en_US/2-create-your-study-forms/3-the-structure-of-castor){target="_blank"}
        + [Field properties: validations (edit checks) and dependencies(field logic) in EDC/CDMS](https://helpdesk.castoredc.com/en_US/fields-and-field-properties/field-properties-validations-edit-checks-and-dependencies-field-logic){target="_blank"}
        + [The 'Users' tab (User Management) in EDC/CDMS](https://helpdesk.castoredc.com/en_US/manage-your-study/the-users-tab-user-management){target="_blank"}
        + [Encryption module](https://helpdesk.castoredc.com/en_US/encryption-module){target="_blank"}
        + [EDC/CDMS Tips for Data Managers](https://helpdesk.castoredc.com/en_US/tips-for-data-managers/tips-for-data-managers){target="_blank"}
        
### Step 5 {#step5} 

* You should [encrypt](https://helpdesk.castoredc.com/en_US/encryption-module/encrypt-specific-fields){target="_blank"} fields in Castor that contain [highly sensitive](../../Security/PrivacyRisks.html){target="_blank"} information
    + This is a minimum requirement for information like name, date of birth or other [direct identifiers](../definitions/Definitions.html#directID){target="_blank"}
    + If a single field contains a lot of detailed information about a participant, such as an open text field, this should also be encrypted

### Step 6 {#step6}

* When you complete your research you should follow the [Castor guidance](https://helpdesk.castoredc.com/hc/en-us/articles/27247484782749-Can-I-lock-and-archive-my-study-once-it-is-complete){target="_blank"} on ending a study. Additionally you must do the following:
    + After all data have been exported from Castor, they should be securely stored on a VU storage option. 
        + If the data are still being analysed, you can find an appropriate solution via the [VU Storage Finder](https://vu.nl/en/research/storagefinder){target="_blank"}
        + If all analyses are complete and the data only need to be archived, the exported data must be archived in a [VU archive](https://rdm.vu.nl/guides/publish-and-share.html#selecting-an-archive){target="_blank"}
    + Once all of the data have been securely stored or archived at the VU, contact [Castor Support](https://helpdesk.castoredc.com/hc/en-us/requests/new){target="_blank"} to have all of the data stored by Castor deleted. Otherwise the data will be automatically stored on Castor's servers for 25 years.



