---
title: "Archiving @ FGB: Summary of FGB Archiving Guidelines"
date: "`r Sys.Date()`; Version 2.1"
output: 
  html_document:
    theme: cerulean
    anchor_sections: TRUE
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
    includes: 
      after_body: ../../footer.html
---


<style type="text/css">


#TOC {
  left: 0%;
  top: 0%;
}



div.tocify {
  width: 15%;
}

.tocify ul, .tocify li {
  line-height: 25px;
}

.tocify-header .tocify-item {
  font-size: 1.2em;
}

.tocify-subheader .tocify-item {
  font-size: 1.1em;
}

/* following two commands get the text of TOC to indent properly */

.tocify-header {
    text-indent: initial;
}

.tocify-subheader > .tocify-item {
  text-indent: initial;
  padding-left: 2em;
}

/* max-width refused to change below unless I included the !important tag next to it. Found answer on this stack exchange https://stackoverflow.com/questions/34906002/increase-width-of-entire-html-rmarkdown-output 
Seems only to be an issue when using TOC; not required to use !important on pages without TOC */

.main-container {
  max-width: 100% !important;
  padding-right: 5%;
  padding-top: 5%;
  padding-bottom: 10%;
}

/* the follow CSS code allows me to take the automatically included anchor sections (that I made active in the YAML with anchor_sections: TRUE) and change the icon that is shown from a hash to a link symbol from the bootstrap icon library */

a.anchor-section::before {
    content: "&#xe144";
    font-family: 'Glyphicons Halflings';
}

/* need to ensure all text is in Roboto so as to be in-line with VU house style*/

body {
  font-family: 'Roboto', sans-serif;
}

h1.title {
  font-size: 28px;
  text-align: center;
}

h4.date { /* this is to affect the size of the date text in the YAML when it prints in html  */
  font-size: 20px;
  text-align: center;
}

h2 {
  font-size: 28px;
}

h3 {
  font-size: 20px;
}

p {
  font-size: 18px;
}

li {
  font-size: 18px;
  margin: 5px;
}

/* improve contrast for all a-tags and headers for accessibility */

a {
  color: #157bb7;
}

h1, h2, h3, h4 {
  color: #105d89;
}

summary { /* this is copied from the bootstrap css for cerulean; by using the following I can change the text from the summary
class so that if looks like a header within the cerulean theme*/
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-weight: 500;
  font-size: 26px;
  color: #105d89;
}

#indent {
  margin-left: 2em; /* this indents an entire paragraph */
}

#negindent {
  margin-left: -2.5em; /* this reduces the indent of an entire paragraph; moves it left */
}

/* make sure colour for reference text isn't too light; for constrast grey cannot be light than #737373 */

.reference {
  font-style: italic;
  color: #737373;
}

</style>

## Introduction {#introduction}

The following is a summary of the [FGB Implementation of the National Guidelines for Archiving of Academic Research for Faculties of Behavioural and Social Sciences](ArchivingGuidelinesFull.html){target="_blank"}. This summary highlights the major concerns when archiving data; in-depth explanation is found in the full guidelines.

**NB: The guidelines summarized here refer specifically to [archiving](../definitions/Definitions.html#archivingdata){target="_blank"} data for preservation purposes; they do not address the complexities involved with the [reuse](../definitions/Definitions.html#reusedata){target="_blank"} of data by third parties.**

-------------------------

## Why Archiving? {#whyarchive}

Data and supplementary materials from your research should be archived because:

* Archiving promotes research integrity and transparency by:
  + Ensuring that research results can be verified, reproduced and, where possible, replicated
  + Providing assurances that data have not been inappropriately tampered with after collection
* Archiving preserves valuable data and the materials necessarily for the proper interpretation of this data well into the future
* Archiving data is important for the safety of your participants when conducting medical research 
  + The archived data serves as a record of the medical interventions that each participant experienced
  + This information is important for safety monitoring and long-term follow-up

<br>
<div class="reference">
Summarized from guideline sections: [1](ArchivingGuidelinesFull.html#section1){target=_blank} and [1.1](ArchivingGuidelinesFull.html#section1.1){target=_blank}
</div>


## What to Archive? {#whatarchive}

You should archive whatever would be necessary to properly interpret your data. This includes data, but also documentation about the data and the research process, as well as code scripts used in the process of your research

* There should be sufficient documentation in the archived materials so that another researcher could reanalyse your data and reproduce your research results without ever contacting you. 
* [Section 2.1.1](ArchivingGuidelinesFull.html#subsection4){target="_blank"} of the full guidelines lists the kinds of materials you are expected to archive. Not everything listed will necessarily apply to your research.


<!--add the following point when the data package page (NEED TO UPDATE NAME OF THAT PAGE) is finished
* The data and supporting materials you will archive are referred to in the guidelines as a [data package](../definitions/Definitions.html#archivingpackage){target="_blank"}. More details on what you should include in your data package based on the types of data you use in your research can be found [here](ArchivingPackage.html){target="_blank"}.
-->
<br>
<div class="reference">
Summarized from guideline sections: [2.1](ArchivingGuidelinesFull.html#section2.1){target=_blank}, [2.1.1](ArchivingGuidelinesFull.html#section2.1.1){target=_blank} and [2.1.2](ArchivingGuidelinesFull.html#section2.1.2){target=_blank}
</div>

<!--Could maybe add a statement here about PURE registration?-->


## When to Archive? {#whenarchive} 

A data package *must* be archived whenever you publish a research article. Researchers are expected to manage their data efficiently during the course of their research so that they can archive the data and supporting materials **as soon as their research article is accepted for publication**. 
 
Additionally, archiving is recommended, but not required, when:

* Data collection for a [research project](../definitions/Definitions.html#researchproject){target="_blank"} has finished, so that the raw data can be stored in a way that prevents (unintentional) modification
* A [research project](../definitions/Definitions.html#researchproject){target="_blank"} is complete, even if the data are not used in any research publications

<br>
<div class="reference">
Summarized from guideline sections: [1.1](ArchivingGuidelinesFull.html#section1.1){target=_blank} and [2.2](ArchivingGuidelinesFull.html#section2.2){target=_blank}
</div>


## Where to Archive? {#wherearchive} 

<!--Include the follow section when further along with a page on the various archives and which one to pick
* The choice of archive depends mainly on the privacy and security risks of the data and materials in the archiving package. See this [page](SecureArchiving.html){target="_blank"} for more information on which archive to choose.
-->

<!--Can also delete or modify this following statement when the more detailed page on picking an archive is complete
-->
The vast majority of data used within the faculty is considered [personal data](../definitions/Definitions.html#personaldata){target="_blank"} and therefore should be stored in a secure archive. The default archive at FGB for most situations and data types is [YODA](../tools/YODAInstructionsFGB.html){target="_blank"}.

* If your data are low enough risk and/or can be [de-identified](../../Security/Deidentification.html){target="_blank"}[*](#deIDnote) enough that they fall under the "Green" category from the [Privacy Risk categorization](../../Security/PrivacyRisks.html){target="_blank"}, then you can use [DataverseNL](https://dataverse.nl/dataverse/vuamsterdam){target="_blank"} instead of YODA if YODA does not meet your requirements.
* If your data are low enough risk and/or can be [de-identified](../../Security/Deidentification.html){target="_blank"}[*](#deIDnote) enough that they fall under the "Blue" category from the [Privacy Risk categorization](../../Security/PrivacyRisks.html){target="_blank"}, then you can use [DataverseNL](https://dataverse.nl/dataverse/vuamsterdam){target="_blank"} or an external [data repository](https://www.re3data.org/){target="_blank"} instead of YODA if YODA does not meet your requirements.
  + You should check with the [FGB Privacy Champion](research.data.fgb@vu.nl) that your data are indeed "Blue" data before archiving them in an external data repository.
* If your data cannot be de-identified to the "Green" or "Blue" category level, it may still be possible to archive the supporting materials (e.g. research code, codebooks, interview scipts etc.) in archives or data repositories other than YODA. Just make sure these supporting materials don't contain any personal or [confidential information](../../Security/PrivacyRisks.html#confidentiality){target="_blank"}.

<div id="deIDnote"></div>
&#42; **It is *very* important to remember that when you are de-identifying your data that you do not irrevocably modify the raw data. Irrevocable modification defeats the purpose of archiving unadulterated raw data. See [How Do I Meet Privacy and Security Requirements?](#privacy_security) for further explanation.**

<br>
<div class="reference">
Summarized from guideline sections: [1.3](ArchivingGuidelinesFull.html#section1.3){target=_blank}, [2.1.1](ArchivingGuidelinesFull.html#subsection4){target=_blank} and [3.3](ArchivingGuidelinesFull.html#section3.3){target=_blank}
</div>

## Who Needs to Archive? {#whoarchive}

### Who do the guidelines apply to? {#guidelinesapply}

* The FGB archiving guidelines apply to all researchers conducting research within the faculty. 

* It also applies to Bachelor's or one-year Master's students **if their research results in a research publication**. 
  + For Bachelor's and one-year Master's students who don't publish any research articles, it is still recommended that they provide an informal data package of their work to their supervisor as a way to practice archiving. The supervisor can decide whether these materials needs to be preserved.


### Who is responsible for archiving? {#responsibleparty}

* If you are the first author on a research paper, you are responsible for archiving. If the first author works at another research facility, you should make sure that the first author will ensure that the data are archived.

* If data are archived for preservation purposes after data collection or upon completion of a research project, the lead researcher is responsible for archiving.

* For research from PhD candidates, Master's and Bachelor's students, the supervisor is responsible for archiving; they may delegate the task to be completed by their student, but they remain ultimately responsible for this task.

* The final responsibility for all archiving in the faculty lies with the dean.



### Who should have access to the archived data? {#accessrequirements}

* Whoever is responsible for archiving should have access to the archived data and supporting materials.
  + There should also be at least one other person who also has access to the archived materials.

<br>
<div class="reference">
Summarized from guideline sections: [1.2](ArchivingGuidelinesFull.html#section1.2){target=_blank}, [2.3](ArchivingGuidelinesFull.html#section2.3){target=_blank} and [2.4](ArchivingGuidelinesFull.html#section2.4){target=_blank}
</div>


## How Long Should Archiving Last? {#howlong}

The duration of archiving depends on the reason you are archiving as well as on other policies and laws.

* For research that isn't subject to the [WMO law](https://english.ccmo.nl/investigators/legal-framework-for-medical-scientific-research/your-research-is-it-subject-to-the-wmo-or-not){target="_blank"}, the [Good Clinical Practice (GCP) Guidelines](https://www.ema.europa.eu/en/documents/scientific-guideline/guideline-content-management-archiving-clinical-trial-master-file-paper/electronic_en.pdf){target="_blank"} or the other regulations mentioned in [section 1.1](ArchivingGudelinesFull.html#section1.1){target="_blank"} of the full archiving guidelines:
  + The data and supporting materials used in the publication of a research article must be archived for 10 years from the date of publication
    + If the data are reused for new research articles, this archiving term should be extended for another 10 years from the new publication date
  + If you chose to archive data after data collection was completed or upon the completion of a research project, even if the data have not (yet) been used for a research article, you can determine how long the data should be archived


* If you are conducting medical research, the duration of archiving will depend on which laws and regulations apply. To determine which archiving duration applies, see this [page](https://english.ccmo.nl/investigators/data-retention-periods-for-medical-research){target="_blank"} from the CCMO or [section 3.1](ArchivingGuidelinesFull.html#section3.1){target=_blank} from the full archiving guidelines

  
* Any data that falls under the "Blue" category from the [Privacy Risk categorization](../../Security/PrivacyRisks.html){target="_blank"} and/or supporting materials that don't contain any [personal](../definitions/Definitions.html#personaldata){target="_blank"} and/or [confidential information](../../Security/PrivacyRisks.html#confidentiality){target="_blank"} can be archived indefinitely, unless any other contracts or agreements apply that limit the archiving duration. 

<br>
<div class="reference">
Summarized from guideline section: [3.1](ArchivingGuidelinesFull.html#section3.1){target=_blank}
</div>


## How Do I Meet Privacy and Security Requirements? {#privacy_security}

It is important that the archived data are protected, particularly when these data are considered [personal](../definitions/Definitions.html#personaldata){target="_blank"}, but you must also ensure that the integrity of the raw data is maintained. 

* Raw data can usually be [de-identified](../../Security/Deidentification.html){target="_blank"}, but it's important that they are not irrevocably altered in the process. Generally, you can  de-identify the data up to step 4 of this de-identification [guide](../../Security/Deidentification.html#Step_4:_Separate_the_direct_identifiers_from_research_data){target="_blank"} without irrevocably altering the raw data. **Only de-identify raw data to a point where it could be returned to its original state**.
* You will need to determine whether any [directly identifying](../definitions/Definitions.html#directID){target="_blank"} personal data collected in the course of your research need to be archived[**](#consentterm) and, if so, for how long. Also determine whether it's necessary to re-identify any de-identified data.
  + This will depend on the nature of your research and what regulations apply. [Section 3.2](ArchivingGuidelinesFull.html#section3.2){target="_blank"} of the full guidelines explains in detail what is required.
* If raw data are separated into [directly identifying](../definitions/Definitions.html#directID){target="_blank"} personal data and de-identified research data, you may: 
  + Archive the de-identified research data in a less secure archive if the data are sufficiently low risk (see [Where to Archive](#wherearchive)). The personal data must be archived in a separate, highly secure archive. Make sure to cross-reference these separate archiving submissions to each other in your documentation.
  + Archive both sets of data in a single, highly secure archive, but submit the personal data separately from the de-identified research data (in other words, create two submissions). Make sure to cross-reference the two submissions to each other in your documentation 
* If the raw data cannot be separated into personal data and de-identified research data without irrevocably altering the raw data, archive all of the data together in a secure archive (see [Where to Archive](#wherearchive))
* You may consider encrypting the personal data (or all of the data if the personal data cannot be separated from the research data), but you must ensure that you have a plan for the long-term management of the de-encryption key. When using YODA as an archive, your best option is to contact the YODA administrator to provide them with a copy of the de-encryption key, and then print a copy of the key and store it in your department's paper archive.

<div id="consentterm">

**One reason you may need to preserve [directly identifying](../definitions/Definitions.html#directID){target="_blank"} personal data is if you obtained consent from participants for the use of their data in your research. You must save these consent forms for as long as the data will be archived.

* The forms need to be saved to serve as evidence that consent was legally obtained. Depending on the nature of the research, the link between the consent form and the data itself may or may not need to be maintained. [Section 3.2](ArchivingGuidelinesFull.html#section3.2){target="_blank"} of the full guidelines explains this further. Once the archiving term is complete, assess whether the research data can be destroyed. Once the research data are destroyed the consent forms should also be destroyed.
* Even if the consent forms do not include any personal data, it is still necessary to save the consent forms for the same duration as the archived research data.
* If paper consent forms were scanned into a digital form, it is not allowed to destroy the original paper copies if your research is subject to the WMO. For non-WMO research, you may destroy the consent forms after digitization as long as you follow the [faculty-approved digitization guidelines](DigitizingICFs.html){target="_blank"}. See this [statement](ArchivingGuidelinesFull.html#paperarchiving){target="_blank"} in the full guidelines for more information.
</div>

<br>
<div class="reference">
Summarized from guideline sections: [1.3](ArchivingGuidelinesFull.html#section1.3){target=_blank}, [2.1.1](ArchivingGuidelinesFull.html#subsection4){target=_blank}, [3.2](ArchivingGuidelinesFull.html#section3.2){target=_blank} and
[3.3](ArchivingGuidelinesFull.html#section3.3){target=_blank}
</div>

## Anything else? {#addtl_info}

Archived data must be persistently findable when the data are used in a research publication. Archived data must also be registered in PURE for VU administrative purposes. FGB researchers can meet these requirements by archiving their data in YODA and publishing those data, even if the data are kept closed or restricted access to prevent/limit [data reuse](../definitions/Definitions.html#reusedata){target="_blank"} of the data. The metadata published in YODA will be automatically uploaded to PURE, meaning the researcher is not required to make a separate PURE registration. 

<br>
<div class="reference">
Summarized from guideline section: [4](ArchivingGuidelinesFull.html#purereg){target=_blank}
</div>

