---
title: "Archiving @ FGB: Data Packages"
date: "`r Sys.Date()`; Version 1.2"
output: 
  html_document:
    theme: cerulean
    anchor_sections: TRUE
    includes: 
      after_body: ../../footer.html
---

## {#CSS}

<style type="text/css">

/* need to ensure all text is in Roboto so as to be in-line with VU house style*/

body {
  font-family: 'Roboto', sans-serif;
}

/* the follow CSS code allows me to take the automatically included anchor sections (that I made active in the YAML with anchor_sections: TRUE) and change the icon that is shown from a hash to a link symbol from the bootstrap icon library */

a.anchor-section::before {
    content: "&#xe144";
    font-family: 'Glyphicons Halflings';
}


/* 2022-10-11: I made the max-width on this particular document 2000px when all the others were at 1600px; this is because I noticed an issue with the positioning of the tabsets (they aren't right next to each other as desired) when in full screen mode on the wide screen monitor. Will check if this is an issue on other pages and adjust max-width as necessary */

.main-container {
  max-width: 90%;
  margin-left: auto;
  margin-right: auto;
  padding-top: 5%;
  padding-bottom: 20%;
  padding-right: 10%;
  padding-left: 10%;
}

h1.title {
  font-size: 28px;
  text-align: center;
}

h4.date { /* this is to affect the size of the date text in the YAML when it prints in html  */
  font-size: 20px;
  text-align: center;
}

/* improve contrast for all a-tags and headers for accessibility */

a {
  color: #157bb7;
}

h1, h2, h3, h4 {
  color: #105d89;
}

p, summary {
  font-size: 18px;
}

li {
  font-size: 18px;
  margin: 5px;
}

summary {
  font-weight: bold;
}

.tabset-dropdown > .nav-tabs {
  width: 100%;
  border-right: none;
  border-left: none;
}


/* to adjust the text of the titles in the tabs need to highlight which tabset I am working with and then follow the tips for adjusting bootstrap nav-tabs that I found here https://stackoverflow.com/questions/36614648/how-do-i-change-color-and-font-of-my-bootstrap-nav-tabs*/

.tabset-dropdown .nav-tabs > li.active > a {
  font-size: 22px;
}

.tabset-fade .nav-tabs > li.active > a {
  font-size: 20px;
}


.tabset h5 {
  font-size: 20px;
}


/* to adjust font-size of paragraph text within a tabset, need to first select the tabset div, then select the class selector of the div surrounding the p text (if I only want to change some of the p text) and then the element p*/


.tabset .NB p {
  font-size: 18px;
  font-style: italic;
  color: #808080;
}


.tabset .NB_alt p {
  margin-left: -2em;
  font-size: 18px;
  font-style: italic;
  color: #808080;
}


.tabset .NB_alt2 p {
  margin-left: 2em;
  font-size: 18px;
  font-style: italic;
  color: #808080;
}


.footnotes {
  margin-top: 10%;
}



</style>




\ <!--this adds a space  -->

## {#intro}

When [it's time](ArchivingGuidelinesSummary.html#whenarchive){target="_blank"} to [archive](../definitions/Definitions.html#archivingdata){target="_blank"} your research data, you'll need to prepare a [data package](../definitions/Definitions.html#datapackage){target="_blank"} which contains not just the research data but the information necessary to interpret the data, as well as a record of what you did with the data. The following guide will help you determine what should be included in a data package depending on the kind(s) of data you are working with.

<!-- I've commented this out for now because I don't have a good page to reference to about publishing data. So will just have to trust that researchers understand the difference. Too much text will be confusing-->

<!--**NB: The guidance in this document is about [archiving data](../definitions/Definitions.html#archivingdata){target="_blank"} not [publishing data](../definitions/Definitions.html#publishingdata){target="_blank"}. Further guidance on publishing data will be available soon** -->

<!--**WILL LINK TO PUBLISHING DATA PAGE WHEN CREATED**-->


## Standard data package requirements {#standard}

Most data packages created by FGB researchers will be archived in [YODA](https://rdm.vu.nl/tools/yoda/cost_access.html){target="_blank"}. Using this [YODA archiving checklist](../../Images/meta_archiving_guide_yoda.docx) will help you meet most of your standard requirements.

### Standard documentation

The data package must include the following documentation:

* A [README file](ArchivingGuidelinesFull.html#subsection9){target="_blank"}
  + [Download FGB README template](https://fgb-rdm.nl/rdm/archiving/README_template.md){target="_blank"}
* A record of your [research data's provenance](https://rdm.vu.nl/guides/process-and-analyse.html#data-provenance){target="_blank"}, e.g.:
  + [A logbook or laboratory notebook](../definitions/Definitions.html#logbook)
* Description of the research design and process, e.g.:
  + Research manuscript, if available
  + Research protocol/pre-registration
  + Research proposal
* A VU custom license if the data package will be [restricted](https://fgb-rdm.nl/rdm/definitions/Definitions.html#restrPubl){target="_blank"} or [closed](https://fgb-rdm.nl/rdm/definitions/Definitions.html#closedPubl){target="_blank"}
  + [VU Restricted License](https://rdm.vu.nl/tools/yoda/workflow_metadata_licence.html#restricted){target="_blank"}
  + [VU Closed License](https://rdm.vu.nl/tools/yoda/workflow_metadata_licence.html#closed){target="_blank"}

### Standard data requirements

The data package that will be archived must include: 

* The original raw data that you collected
  + If existing data were reused, include a link to the permanent identifier (e.g. DOI) of the data used (including the version, if applicable)
* The processed data used in the research analysis

#### Additional data considerations

* Whenever possible, the data files in the data package must be in [open source and/or preferred formats](https://ukdataservice.ac.uk/learning-hub/research-data-management/format-your-data/recommended-formats/){target="_blank"}
  + If your data were in a proprietary format (e.g. xls or sav files), include a copy of the data in that format
* Use logical naming systems for your files and folders
  + &#x2705; "analysis_data_v1.2_20260505.csv"
  + &#x274C; "finalversion_final_final.sav"
* If you plan to [openly publish](https://fgb-rdm.nl/rdm/definitions/Definitions.html#publishingdata){target="_blank"} (some of) the research data, organize your data package so that only the data that *can* be openly published *is* openly published.
  + When you have some data that will be openly published and some that will be restricted or closed, it's best to create more than one data package and cross-reference them to each other in your README/metadata.



\








## Data-specific data package requirements {#dataspecificreq}

Different types of data used in a various kinds of research will have specific requirements when included in a data package. Use the following search bar for look for your research or data type to get more information on what is required for your specific data. If you aren't sure, you can review all of the specifications by clicking "Show All". If you still are not sure or cannot find information specific to your situation, please contact [research.data.fgb@vu.nl](mailto:research.data.fgb@vu.nl).


``` {r, echo=FALSE}


library(jsonlite)

# read in data_documentation table

csv_data <- read.csv("data/data_documentation.csv", stringsAsFactors = FALSE)

# convert to JSON

json_data <- jsonlite::toJSON(csv_data)


```



<div style="margin: 20px 0; text-align: center;">
  <input type="text" id="searchBar" placeholder="Search research or data types..." 
         style="width: 60%; padding: 10px; font-size: 16px;"
         onkeypress="handleKeyPress(event)">
  <button onclick="performSearch()" style="padding: 10px 20px;">Search</button>
  <button onclick="performSearch(true)" style="padding: 10px 20px;">Show All</button>
</div>

<div id="resultsContainer"></div>




<script>

const data = '`r json_data`';
const parsedData = JSON.parse(data);

// create map of links to insert into html

const linkMap = {
  "BIDS": "https://bids-specification.readthedocs.io/en/stable/introduction.html",
  "BIDS (behavioral)": "https://bids-specification.readthedocs.io/en/stable/modality-specific-files/behavioral-experiments.html",
  "CDISC": "https://www.cdisc.org/standards",
  "Codebook/data dictionary": "https://fgb-rdm.nl/rdm/documentation/Codebooks.html",
  "Coding framework": "https://fgb-rdm.nl/rdm/documentation/Codebooks.html#codebooks-for-qualitative-data",
  "DDI": "https://ddialliance.org/product_overview",
  "Dublin Core": "https://www.dublincore.org/specifications/dublin-core/dcmi-terms/",
  "HL7 FHIR": "https://www.hl7.org/fhir/overview.html",
  "ISO 19115": "https://docs.geostandaarden.nl/md/mdprofiel-iso19115/",
  "Logbook/laboratory notebook": "https://fgb-rdm.nl/rdm/definitions/Definitions.html#logbook",
  "MIAME": "https://www.ncbi.nlm.nih.gov/geo/info/MIAME.html",
  "MINSEQE": "https://doi.org/10.5281/zenodo.5706412",
  "OpenSim": "https://opensimconfluence.atlassian.net/wiki/spaces/OpenSim/pages/53090607/Musculoskeletal+Models#OpenSim-Core-Models",
  "Procedures to manage coder variance": "https://dmeg.cessda.eu/Data-Management-Expert-Guide/3.-Process/Qualitative-coding",
  "See guidelines on paper archiving": "https://fgb-rdm.nl/rdm/archiving/ArchivingGuidelinesFull.html#paperarchiving",
  "SensorML": "https://www.ogc.org/standards/sensorml/",
  "TEI": "https://tei-c.org/release/doc/tei-p5-doc/en/html/index.html"
  
};

// This function checks if the pressed key is "Enter"

function handleKeyPress(event) {
  if (event.key === "Enter") {
    performSearch();
  }
};

// function to capitalize first letter of strings 

function capitalizeFirstLetter(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
}

// function to split string on | , clean up raw text, add in hyperlinks if present in linkMap and combine text as <ul>

function createListFromText(rawString, lookupMap = {}) {
  if (!rawString || rawString.trim() === "") return "<em>n/a</em>"; // Handle empty data

  const items = rawString.split('|');
  
  const listItems = items.map(item => {
    const trimmedItem = capitalizeFirstLetter(item.trim());
      // run capitalizeFirstLetter on each element for consistent formatting
      // also run trim() to remove any leading/trailing spaces
    
      // If the item name exists in lookupMap, create a link; otherwise, return text formatted as <li></li>
    if (lookupMap[trimmedItem]) {
      return `<li><a href='${lookupMap[trimmedItem]}' target='_blank'>${trimmedItem}</a></li>`;
    }
    // Otherwise, just return the plain list item
    return `<li>${trimmedItem}</li>`;
  }).join(''); // Join elements back together
  
  return `<ul>${listItems}</ul>`;
}



// function to search on research type, data examples or keywords and return formatted results

function performSearch(showAll = false) {
  const query = document.getElementById('searchBar').value.toLowerCase();
  const container = document.getElementById('resultsContainer');
  container.innerHTML = ""; // Clear previous

  // Filter logic: Show all if flag is true, otherwise filter by query
  const filtered = showAll ? parsedData : parsedData.filter(item => 
    item.research_type.toLowerCase().includes(query) || 
    item.data_example.toLowerCase().includes(query) || 
    item.keywords.toLowerCase().includes(query)
  );
  
  // Handle No Results
  if (filtered.length === 0) {
    container.innerHTML = `
      <p style="text-align: center; color: #666;">
        No results found. 
        <a href="javascript:void(0)" onclick="performSearch(true)" style="color: #105d89;">Show all instead?</a>
      </p>`;
    return;
  }

  filtered.forEach(item => {
  
    // use createListFromText to generate lists (and where appropriate hyperlinks) from text fields in csv
    
    const formatList = createListFromText(item.preferred_format, linkMap);
    const metadataList = createListFromText(item.metadata_standard, linkMap);
    const readmeList = createListFromText(item.readme_additions, linkMap);
    const docsList = createListFromText(item.documentation_required, linkMap);
    
  
    container.innerHTML += `
        <div style="padding: 20px; background-color: #f9f9f9; border: 1px solid #105d89; margin-bottom: 15px;">
          <h3 style="color: #105d89;">${item.research_type}</h3>
          <h4 style="color: #105d89;">Examples:</h4>
          <p>${item.data_example}</p>
          <h4 style="color: #105d89;">Preferred Format(s):</h4>
          ${formatList}
          <h4 style="color: #105d89;">Metadata Standard(s):</h4>
          ${metadataList}
          <h4 style="color: #105d89;">Additions to README:</h4>
          ${readmeList}
          <h4 style="color: #105d89;">Required Documentation:</h4>
          ${docsList}
        </div>
      `;
  });
}
</script>






